name: Deploy to Dev Server

on:
  push:
    branches: [ main ] # The branch we need to watch on push
  pull_request:
    branches: [ main ] # The branch we need to watch on pull request merge

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Copy files to the remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "."
          target: "${{ secrets.WORK_DIR }}"
